$ErrorActionPreference = "Continue"

$Root = "C:\IEPDF\frontend"
$ReportDir = Join-Path $Root "_regression\merge-pdf"
$Stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$Report = Join-Path $ReportDir "merge-runtime-chunk-react-v10-$Stamp.txt"

New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null

$Out = New-Object System.Collections.Generic.List[string]

function Add-Line {
    param([string]$Text = "")
    $Value = [string]$Text
    $Out.Add($Value)
    Write-Host $Value
}

function Section {
    param([string]$Title)

    Add-Line ""
    Add-Line ("=" * 80)
    Add-Line $Title
    Add-Line ("=" * 80)
}

function SafeRead {
    param([string]$Path)

    try {
        if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
            return $null
        }

        return [System.IO.File]::ReadAllText($Path)
    }
    catch {
        return $null
    }
}

function TestPattern {
    param(
        [string]$Text,
        [string]$Pattern
    )

    if ($null -eq $Text) {
        return $false
    }

    return $Text.Contains($Pattern)
}

Add-Line "iePDF MERGE PDF - RUNTIME CHUNK & REACT RENDER IDENTITY AUDIT V10"
Add-Line "Started: $(Get-Date)"
Add-Line "Root: $Root"
Add-Line ""
Add-Line "READ ONLY"
Add-Line "NO SOURCE CHANGES"
Add-Line "NO GIT"
Add-Line "NO DEPLOYMENT"
Add-Line "NO CACHE DELETION"

# ============================================================
# 1. CURRENT SOURCE HASH / SIZE
# ============================================================

Section "1. CURRENT SOURCE IDENTITY"

$CurrentComponent = Join-Path $Root "components\MergeWorkspace.tsx"
$CurrentPage = Join-Path $Root "app\merge-pdf\page.tsx"

foreach ($Path in @($CurrentComponent, $CurrentPage)) {

    if (Test-Path -LiteralPath $Path) {

        $Info = Get-Item -LiteralPath $Path

        Add-Line ""
        Add-Line "FILE: $Path"
        Add-Line "SIZE: $($Info.Length)"
        Add-Line "LASTWRITE: $($Info.LastWriteTime)"

        try {
            $Hash = Get-FileHash -LiteralPath $Path -Algorithm SHA256
            Add-Line "SHA256: $($Hash.Hash)"
        }
        catch {
            Add-Line "SHA256: unavailable"
        }

    }
    else {

        Add-Line ""
        Add-Line "MISSING: $Path"
    }
}

# ============================================================
# 2. ALL .NEXT CHUNKS
# ============================================================

Section "2. GENERATED NEXT CHUNKS"

$NextStatic = Join-Path $Root ".next\static"

if (-not (Test-Path -LiteralPath $NextStatic)) {

    Add-Line "FAIL: .next/static does not exist"

}
else {

    $Chunks = @(
        Get-ChildItem `
            -LiteralPath $NextStatic `
            -Recurse `
            -File `
            -ErrorAction SilentlyContinue |
        Where-Object {
            $_.Extension -in @(".js",".map")
        }
    )

    Add-Line "Generated JS/map files: $($Chunks.Count)"

    $TotalBytes = 0

    foreach ($File in $Chunks) {
        $TotalBytes += $File.Length
    }

    Add-Line "Total generated bytes: $TotalBytes"
}

# ============================================================
# 3. SEARCH CURRENT COMPONENT SIGNATURE IN ALL CLIENT CHUNKS
# ============================================================

Section "3. CLIENT CHUNK SEARCH - CURRENT COMPONENT SIGNATURE"

$Patterns = @(
    "application/x-iepdf-reorder",
    "Add PDF Files",
    "Unlock & Merge",
    "Drag & drop PDFs here",
    "Processing happens in your browser",
    "files.map",
    "onReorderFiles",
    "onUnlockMerge",
    "onAddFiles"
)

foreach ($Pattern in $Patterns) {

    Add-Line ""
    Add-Line "PATTERN: $Pattern"

    $Matches = @()

    foreach ($File in $Chunks) {

        $Text = SafeRead $File.FullName

        if (TestPattern $Text $Pattern) {

            $Matches += $File
        }
    }

    if ($Matches.Count -eq 0) {

        Add-Line "  NOT FOUND"

    }
    else {

        Add-Line "  FOUND IN: $($Matches.Count) FILE(S)"

        foreach ($Match in $Matches) {

            Add-Line "  $($Match.FullName)"
            Add-Line "    SIZE: $($Match.Length)"
        }
    }
}

# ============================================================
# 4. SEARCH OLD UI SIGNATURE
# ============================================================

Section "4. CLIENT CHUNK SEARCH - OLD UI SIGNATURE"

$OldPatterns = @(
    "Select PDF Files",
    "showWorkspace",
    "setShowWorkspace",
    "workspaceFiles",
    "processSelectedFiles",
    "BrowserPdfAnalyzer"
)

foreach ($Pattern in $OldPatterns) {

    Add-Line ""
    Add-Line "OLD PATTERN: $Pattern"

    $Matches = @()

    foreach ($File in $Chunks) {

        $Text = SafeRead $File.FullName

        if (TestPattern $Text $Pattern) {
            $Matches += $File
        }
    }

    if ($Matches.Count -eq 0) {

        Add-Line "  NOT FOUND"

    }
    else {

        Add-Line "  FOUND IN: $($Matches.Count) FILE(S)"

        foreach ($Match in $Matches) {
            Add-Line "  $($Match.FullName)"
        }
    }
}

# ============================================================
# 5. MERGEWORKSPACE SOURCE MAP SEARCH
# ============================================================

Section "5. SOURCE MAP IDENTITY SEARCH"

$MapFiles = @(
    $Chunks |
    Where-Object {
        $_.Extension -eq ".map"
    }
)

Add-Line "Source maps: $($MapFiles.Count)"

foreach ($Map in $MapFiles) {

    $Text = SafeRead $Map.FullName

    if ($null -ne $Text) {

        $FoundComponent = TestPattern $Text "components/MergeWorkspace.tsx"
        $FoundPage = TestPattern $Text "app/merge-pdf/page.tsx"
        $FoundComponentName = TestPattern $Text "MergeWorkspace"

        if ($FoundComponent -or $FoundPage -or $FoundComponentName) {

            Add-Line ""
            Add-Line "RELEVANT MAP: $($Map.FullName)"
            Add-Line "  component path: $FoundComponent"
            Add-Line "  page path: $FoundPage"
            Add-Line "  component name: $FoundComponentName"
            Add-Line "  size: $($Map.Length)"
        }
    }
}

# ============================================================
# 6. CLIENT REFERENCE MANIFESTS
# ============================================================

Section "6. CLIENT REFERENCE MANIFESTS"

$ManifestFiles = @(
    Get-ChildItem `
        -LiteralPath (Join-Path $Root ".next") `
        -Recurse `
        -File `
        -ErrorAction SilentlyContinue |
    Where-Object {
        $_.Name -like "*client-reference-manifest*"
    }
)

Add-Line "Client reference manifests: $($ManifestFiles.Count)"

foreach ($Manifest in $ManifestFiles) {

    Add-Line ""
    Add-Line "MANIFEST: $($Manifest.FullName)"
    Add-Line "SIZE: $($Manifest.Length)"
    Add-Line "LASTWRITE: $($Manifest.LastWriteTime)"

    $Text = SafeRead $Manifest.FullName

    if ($null -ne $Text) {

        if ($Text.Contains("MergeWorkspace")) {
            Add-Line "  MergeWorkspace reference: PRESENT"
        }
        else {
            Add-Line "  MergeWorkspace reference: ABSENT"
        }

        if ($Text.Contains("components/MergeWorkspace")) {
            Add-Line "  components/MergeWorkspace path: PRESENT"
        }
        else {
            Add-Line "  components/MergeWorkspace path: ABSENT"
        }
    }
}

# ============================================================
# 7. SERVER RUNTIME REFERENCES
# ============================================================

Section "7. SERVER RUNTIME REFERENCES"

$ServerRoot = Join-Path $Root ".next\server"

if (Test-Path -LiteralPath $ServerRoot) {

    $ServerFiles = @(
        Get-ChildItem `
            -LiteralPath $ServerRoot `
            -Recurse `
            -File `
            -ErrorAction SilentlyContinue |
        Where-Object {
            $_.Extension -eq ".js" -or
            $_.Extension -eq ".map"
        }
    )

    Add-Line "Server JS/map files: $($ServerFiles.Count)"

    foreach ($File in $ServerFiles) {

        $Text = SafeRead $File.FullName

        if ($null -ne $Text) {

            if (
                $Text.Contains("MergeWorkspace") -or
                $Text.Contains("application/x-iepdf-reorder") -or
                $Text.Contains("Add PDF Files") -or
                $Text.Contains("Select PDF Files")
            ) {

                Add-Line ""
                Add-Line "SERVER MATCH: $($File.FullName)"
                Add-Line "  MergeWorkspace: $(TestPattern $Text "MergeWorkspace")"
                Add-Line "  reorder marker: $(TestPattern $Text "application/x-iepdf-reorder")"
                Add-Line "  Add PDF Files: $(TestPattern $Text "Add PDF Files")"
                Add-Line "  Select PDF Files: $(TestPattern $Text "Select PDF Files")"
            }
        }
    }
}
else {
    Add-Line ".next/server not found"
}

# ============================================================
# 8. DEV SERVER GENERATED FILES
# ============================================================

Section "8. DEV SERVER RUNTIME REFERENCES"

$DevRoot = Join-Path $Root ".next\dev"

if (Test-Path -LiteralPath $DevRoot) {

    $DevFiles = @(
        Get-ChildItem `
            -LiteralPath $DevRoot `
            -Recurse `
            -File `
            -ErrorAction SilentlyContinue |
        Where-Object {
            $_.Extension -eq ".js" -or
            $_.Extension -eq ".map"
        }
    )

    Add-Line "Dev JS/map files: $($DevFiles.Count)"

    foreach ($File in $DevFiles) {

        $Text = SafeRead $File.FullName

        if ($null -ne $Text) {

            if (
                $Text.Contains("MergeWorkspace") -or
                $Text.Contains("application/x-iepdf-reorder") -or
                $Text.Contains("Add PDF Files") -or
                $Text.Contains("Select PDF Files")
            ) {

                Add-Line ""
                Add-Line "DEV MATCH: $($File.FullName)"
                Add-Line "  MergeWorkspace: $(TestPattern $Text "MergeWorkspace")"
                Add-Line "  reorder marker: $(TestPattern $Text "application/x-iepdf-reorder")"
                Add-Line "  Add PDF Files: $(TestPattern $Text "Add PDF Files")"
                Add-Line "  Select PDF Files: $(TestPattern $Text "Select PDF Files")"
            }
        }
    }
}
else {
    Add-Line ".next/dev not found"
}

# ============================================================
# 9. LEGACY PAGE REFERENCES
# ============================================================

Section "9. LEGACY ROOT MERGE-PDF REFERENCES"

$LegacyDir = Join-Path $Root "merge-pdf"

if (Test-Path -LiteralPath $LegacyDir) {

    Add-Line "Legacy directory PRESENT: $LegacyDir"

    $LegacyFiles = @(
        Get-ChildItem `
            -LiteralPath $LegacyDir `
            -Recurse `
            -File `
            -ErrorAction SilentlyContinue
    )

    foreach ($File in $LegacyFiles) {
        Add-Line "  $($File.FullName)"
    }

    $AllNextFiles = @(
        Get-ChildItem `
            -LiteralPath (Join-Path $Root ".next") `
            -Recurse `
            -File `
            -ErrorAction SilentlyContinue |
        Where-Object {
            $_.Extension -eq ".js" -or
            $_.Extension -eq ".map"
        }
    )

    foreach ($File in $AllNextFiles) {

        $Text = SafeRead $File.FullName

        if ($null -ne $Text) {

            if ($Text.Contains("merge-pdf/page.tsx")) {

                Add-Line ""
                Add-Line "LEGACY PAGE SOURCE REFERENCE FOUND:"
                Add-Line $File.FullName
            }
        }
    }

}
else {

    Add-Line "Legacy directory ABSENT"
}

# ============================================================
# 10. GENERATED ROUTE FILES
# ============================================================

Section "10. GENERATED MERGE ROUTE FILES"

$RouteDirs = @(
    Join-Path $Root ".next\dev\server\app\merge-pdf",
    Join-Path $Root ".next\server\app\merge-pdf"
)

foreach ($Dir in $RouteDirs) {

    if (Test-Path -LiteralPath $Dir) {

        Add-Line ""
        Add-Line "ROUTE DIR: $Dir"

        Get-ChildItem `
            -LiteralPath $Dir `
            -Recurse `
            -File `
            -ErrorAction SilentlyContinue |
        ForEach-Object {

            Add-Line "  $($_.Name)"
            Add-Line "    SIZE=$($_.Length)"
            Add-Line "    LASTWRITE=$($_.LastWriteTime)"
        }
    }
}

# ============================================================
# 11. BUILD IDENTITY
# ============================================================

Section "11. NEXT BUILD IDENTITY"

$BuildId = Join-Path $Root ".next\BUILD_ID"

if (Test-Path -LiteralPath $BuildId) {

    Add-Line "BUILD_ID PRESENT"

    $BuildText = Read-Safe $BuildId

    if ($null -ne $BuildText) {
        Add-Line "BUILD_ID: $($BuildText.Trim())"
    }

}
else {

    Add-Line "BUILD_ID absent"
}

# ============================================================
# 12. FINAL INTERPRETATION
# ============================================================

Section "12. FINAL INTERPRETATION"

Add-Line "SOURCE:"
Add-Line "  Current page: $CurrentPage"
Add-Line "  Current component: $CurrentComponent"

Add-Line ""
Add-Line "RUNTIME QUESTION:"
Add-Line "  Does generated runtime contain the current MergeWorkspace signature?"
Add-Line "  Does generated runtime contain old Merge UI signatures?"
Add-Line "  Does any generated runtime reference the legacy root merge-pdf page?"

Add-Line ""
Add-Line "IMPORTANT:"
Add-Line "Absence of a text string in one page.js file is NOT treated as proof."
Add-Line "Chunks are analyzed collectively."

Add-Line ""
Add-Line "NO SOURCE CHANGES"
Add-Line "NO GIT"
Add-Line "NO DEPLOYMENT"
Add-Line "NO CACHE DELETION"

# ============================================================
# 13. REPORT
# ============================================================

Section "13. REPORT"

Add-Line "Report: $Report"
Add-Line "Finished: $(Get-Date)"

[System.IO.File]::WriteAllLines(
    $Report,
    $Out,
    [System.Text.UTF8Encoding]::new($false)
)

Write-Host ""
Write-Host "============================================================"
Write-Host "V10 RUNTIME CHUNK & REACT IDENTITY AUDIT COMPLETE"
Write-Host "Report: $Report"
Write-Host "NO SOURCE CHANGES"
Write-Host "NO GIT"
Write-Host "NO DEPLOYMENT"
Write-Host "NO CACHE DELETION"
Write-Host "============================================================"